title: "Fabis Blog"
description: ""
remote_theme: jekyll/minima

# Optional, aber praktisch: RSS/Atom Feed
plugins:
  - jekyll-feed

# Kleine Komfort-Optionen
show_excerpts: true

# Optional: Minima-Theme Optionen (z. B. dark/light)
minima:
  skin: auto
