title: "Socioflow Blog"
description: "Socioflow is my space to think through thoughts, prepare argumentation arcs and learn english. "

remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/dark.css"


# Optional, aber praktisch: RSS/Atom Feed
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-remote-theme 
  - jekyll-sitemap

# Statische Dateien (f√ºr eigenes CSS)
sass:
  style: compressed

# Kleine Komfort-Optionen
show_excerpts: true

read_time: true
words_per_minute: 200

search_full_content: true

google_fonts:
  - name: "Merriweather"
    weights: "400,400i,700,700i"
  - name: "Literata"
    weights: "400,400i,700,700i"